### ISSUE TITLE
Plugin wont loaded

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/Nemisys#115]
Hello folks, I tried to write a Nemisys plugin but if I put it into the folder I'll get the following error:
2017-1-15 14:50:38 [ERROR] Could not load 'NetzwerkKern.jar' in folder '/root/Nemisys/plugins': java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.regex.Pattern.matches(Pattern.java:1134)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:175)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:119)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:111)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:107)
	at org.itxtech.nemisys.Server.<init>(Server.java:168)
	at org.itxtech.nemisys.Nemisys.main(Nemisys.java:48)

2017-1-15 14:50:38 [ALERT] java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.regex.Pattern.matches(Pattern.java:1134)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:175)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:119)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:111)
	at org.itxtech.nemisys.plugin.PluginManager.loadPlugins(PluginManager.java:107)
	at org.itxtech.nemisys.Server.<init>(Server.java:168)
	at org.itxtech.nemisys.Nemisys.main(Nemisys.java:48)

What have I made wrong?

Plugin.yml:
name: NetzwerkKern
version: "1.0.0"
author: JackboyPlay
main: me.JackboyPlay.Netzwerkkern.NK

**Comment by JackboyPlay** [comment]
Closed

**Comment by JackboyPlay** [comment]
@boybook whats the default api: in plugin.yml?
