### ISSUE TITLE
'Magic is not match'

### ISSUE THREAD

**Issue by FunnyBuddys** [iTXTech/Nemisys#126]
> 04:44:20 [ERROR] Magic is not match
> io.netty.handler.codec.DecoderException: org.itxtech.nemisys.network.synlib.SynapseContextException: magic value is not equal -17730
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.itxtech.nemisys.network.synlib.SynapseContextException: magic value is not equal -17730
        at org.itxtech.nemisys.network.synlib.SynapsePacketDecoder.checkMagic(SynapsePacketDecoder.java:63)
        at org.itxtech.nemisys.network.synlib.SynapsePacketDecoder.decode(SynapsePacketDecoder.java:33)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        ... 16 more 

Thats the code..

**Comment by VoltexYT** [comment]
Funny es bringt nichts die Antworten eh nicht xd
