### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VoltexYT** [iTXTech/Nemisys#129]
NEMISYS :
> io.netty.handler.codec.DecoderException: org.itxtech.nemisys.network.synlib.SynapseContextException: magic value is not equal -17730
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:422)
        at io.netty.handler.codec.ReplayingDecoder.channelInputClosed(ReplayingDecoder.java:329)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:342)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:235)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.itxtech.nemisys.network.synlib.SynapseContextException: magic value is not equal -17730
        at org.itxtech.nemisys.network.synlib.SynapsePacketDecoder.checkMagic(SynapsePacketDecoder.java:63)
        at org.itxtech.nemisys.network.synlib.SynapsePacketDecoder.decode(SynapsePacketDecoder.java:33)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
        ... 17 more
Server : 
[06:43:42] [SynapseClient thread/NOTICE]: Trying to re-connect to Synapse Server
[06:43:42] [SynapseClient thread/INFO]: Synapse has connected to 127.0.0.1:10305
Please help xd

**Comment by boybook** [comment]
Please be sure the protocol version of Nemisys and SynapseAPI/SynapsePM(maybe not updated) is the same
