### ISSUE TITLE
To many files open

### ISSUE THREAD

**Issue by vvzar** [iTXTech/Nemisys#26]
What can I do to resolve this errors? (Very quickly nonstop repeating at console screen.)
It happens after some normal uptime.

12:08:03 [ALERT] java.io.FileNotFoundException: /mcpe/nemisys/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)

12:08:03 [ALERT] java.io.FileNotFoundException: /mcpe/nemisys/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172) 

I set ulimit -n 4096, hope this help.

**Comment by ghost** [comment]
Use : java -Xms512M -Xmx1024M -jar nemisys.jar

**Comment by vvzar** [comment]
> Use : java -Xms512M -Xmx1024M -jar nemisys.jar
> it doesnt help...
> ulimit -n 4096 does not help too...

**Comment by vvzar** [comment]
I have tried -xms2048 -xmx4096 - uptime increased up to 2 days, but after all I get same error.
Looks like somewhere file descriptors leak, or whatever

```
    at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)
```

09:57:24 [ALERT] java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at org.itxtech.nemisys.network.synlib.SessionManager.tick(SessionManager.java:109)
        at org.itxtech.nemisys.network.synlib.SessionManager.tickProcessor(SessionManager.java:42)
        at org.itxtech.nemisys.network.synlib.SessionManager.run(SessionManager.java:32)
        at org.itxtech.nemisys.network.synlib.SynapseServer.run(SynapseServer.java:128)

09:57:24 [ALERT] java.io.FileNotFoundException: /mcpe/nemisys/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)

09:57:24 [ALERT] java.io.FileNotFoundException: /mcpe/nemisys/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)

09:57:24 [ALERT] java.io.FileNotFoundException: /mcpe/nemisys/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)

09:57:24 [ALERT] java.io.FileNotFoundException: /mcpe/nemisys/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)

09:57:24 [ALERT] java.io.FileNotFoundException: /mcpe/nemisys/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)

**Comment by SleepSpace9** [comment]
I do a daily restart of Nemisys with a log rotate, so the logfile never gets to big. I don't have such an issue.

**Comment by vvzar** [comment]
> I do a daily restart of Nemisys 
> by this action, you dont let nemisys to get to critical condition, but issue is out there :)

**Comment by tarik02** [comment]
I'm also got this error:

```
18:25:33 [ALERT] java.io.FileNotFoundException: ***/server.log (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.itxtech.nemisys.utils.MainLogger.run(MainLogger.java:172)
```

**Comment by dktapps** [comment]
Please head over to #37 and test a fix.

**Comment by XFuryMCPE** [comment]
https://easyengine.io/tutorials/linux/increase-open-files-limit/
