### ISSUE TITLE
[HELP] Getting Exceptions 

### ISSUE THREAD

**Issue by ghost** [iTXTech/Nemisys#45]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/itxtech/nemisys/Nemisys : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by XFuryMCPE** [comment]
No point in this issue to be honest. The staff don't even manage this anymore -_-

**Comment by ghost** [comment]
i know right

**Comment by ghost** [comment]
I installed everything coerectly, but it says that error message ^

**Comment by Matthww** [comment]
Outdated java. You need atleast Java 8 to get it working.

**Comment by ghost** [comment]
I did installed java8 -_- look [here](https://gist.github.com/legoboy0215/62fdf59fe8ec843e9f1d29e35bb67013) @ishitatsuyuki

**Comment by ishitatsuyuki** [comment]
Well, I believe you will finally figure out after running `java -version`.
