### ISSUE TITLE
Error for latest version in console

### ISSUE THREAD

**Issue by MattWAnderson** [iTXTech/Nemisys#54]
Any thoughts? we get this error almost constantly.

2016-9-25 12:58:45 [ALERT] java.lang.NullPointerException
    at org.itxtech.nemisys.event.server.QueryRegenerateEvent.getLongQuery(QueryRegenerateEvent.java:189)
    at org.itxtech.nemisys.network.query.QueryHandler.regenerateInfo(QueryHandler.java:43)
    at org.itxtech.nemisys.network.query.QueryHandler.handle(QueryHandler.java:95)
    at org.itxtech.nemisys.Server.handlePacket(Server.java:340)
    at org.itxtech.nemisys.network.RakNetInterface.handleRaw(RakNetInterface.java:153)
    at org.itxtech.nemisys.raknet.server.ServerHandler.handlePacket(ServerHandler.java:131)
    at org.itxtech.nemisys.network.RakNetInterface.process(RakNetInterface.java:58)
    at org.itxtech.nemisys.network.Network.processInterfaces(Network.java:64)
    at org.itxtech.nemisys.Server.tick(Server.java:380)
    at org.itxtech.nemisys.Server.tickProcessor(Server.java:353)
    at org.itxtech.nemisys.Server.start(Server.java:333)
    at org.itxtech.nemisys.Server.<init>(Server.java:173)
    at org.itxtech.nemisys.Nemisys.main(Nemisys.java:48)

2016-9-25 12:58:45 [NOTICE] Blocked 177.191.44.\* for 600 seconds
2016-9-25 12:58:45 [INFO] LyricWharf13364[/201.150.127.*:26456] logged out due to timeout
2016-9-25 12:58:45 [ALERT] java.lang.NullPointerException
    at org.itxtech.nemisys.event.server.QueryRegenerateEvent.getLongQuery(QueryRegenerateEvent.java:189)
    at org.itxtech.nemisys.network.query.QueryHandler.regenerateInfo(QueryHandler.java:43)
    at org.itxtech.nemisys.Server.tick(Server.java:406)
    at org.itxtech.nemisys.Server.tickProcessor(Server.java:353)
    at org.itxtech.nemisys.Server.start(Server.java:333)
    at org.itxtech.nemisys.Server.<init>(Server.java:173)
    at org.itxtech.nemisys.Nemisys.main(Nemisys.java:48)

**Comment by SleepSpace9** [comment]
Thank you for creating an issue, I wrote my workaround for this problem already to another issue, sorry for mixing it. (https://github.com/iTXTech/Nemisys/issues/51#issuecomment-249439736)
