### ISSUE TITLE
Raknet crach

### ISSUE THREAD

**Issue by Ragnok123** [iTXTech/Nemisys#74]
Hello,  how to fix this?

2016-10-15 13:48:57 [EMERGENCY] RakNet crashed!
2016-10-15 13:48:57 [EMERGENCY] SynLib crashed!
2016-10-15 13:48:57 [ALERT] java.io.IOException: Input/output error
    at java.io.FileInputStream.read0(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:207)
    at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
    at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
    at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
    at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
    at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
    at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136)
    at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126)
    at jline.console.ConsoleReader.readBinding(ConsoleReader.java:2211)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2460)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
    at org.itxtech.nemisys.command.CommandReader.readLine(CommandReader.java:46)
    at org.itxtech.nemisys.command.CommandReader.run(CommandReader.java:60)

**Comment by Ragnok123** [comment]
It doesnt crash at starting, it crash in every 4 hours.

**Comment by PeratX** [comment]
Please provide OS and version
Runtime environment.

**Comment by PeratX** [comment]
Seem like socket stream closed unexpectedly.

**Comment by Ragnok123** [comment]
It's Debian 8, 64 bit.
