### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException on server connection

### ISSUE THREAD

**Issue by jarne** [iTXTech/Nemisys#80]
Since 78c95131cd893edae454fadd8fe697a53314db43, when I'm using the latest Nemisys build (978b1ccda208c86842a55e727728b1a52d78d7ce) @boybook  and the Genisys 0.16 branch, there's an error when Genisys tries to connect to Nemisys:

```
09:25:39 [ALERT] java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at java.util.Arrays.copyOfRange(Arrays.java:3521)
        at org.itxtech.nemisys.utils.BinaryStream.get(BinaryStream.java:77)
        at org.itxtech.nemisys.utils.BinaryStream.getShort(BinaryStream.java:124)
        at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:253)
        at org.itxtech.nemisys.network.protocol.spp.ConnectPacket.decode(ConnectPacket.java:37)
        at org.itxtech.nemisys.network.SynapseInterface.handlePacket(SynapseInterface.java:121)
        at org.itxtech.nemisys.network.SynapseInterface.processPackets(SynapseInterface.java:80)
        at org.itxtech.nemisys.network.SynapseInterface.process(SynapseInterface.java:101)
        at org.itxtech.nemisys.Server.tick(Server.java:381)
        at org.itxtech.nemisys.Server.tickProcessor(Server.java:353)
        at org.itxtech.nemisys.Server.start(Server.java:333)
        at org.itxtech.nemisys.Server.<init>(Server.java:173)
        at org.itxtech.nemisys.Nemisys.main(Nemisys.java:48)

09:25:44 [ERROR] Client 127.0.0.1:47224 is not verified
```

**Comment by jjplaying** [comment]
Found the bug, 0.16 branch of Genisys is using the wrong genisys.yml item (password instead of server-password) (https://github.com/iTXTech/Genisys/blob/0.16/src/synapse/Synapse.php#L77).
