### ISSUE TITLE
Synapse client(Genisys) can't connect to Nemisys

### ISSUE THREAD

**Issue by tarik02** [iTXTech/Nemisys#81]
I'm get this error when genisys is trying to connect to nemisys:

```
19:06:43 [ALERT] java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at java.util.Arrays.copyOfRange(Unknown Source)
        at org.itxtech.nemisys.utils.BinaryStream.get(BinaryStream.java:77)
        at org.itxtech.nemisys.utils.BinaryStream.getShort(BinaryStream.java:124)
        at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:253)
        at org.itxtech.nemisys.network.protocol.spp.ConnectPacket.decode(ConnectPacket.java:37)
        at org.itxtech.nemisys.network.SynapseInterface.handlePacket(SynapseInterface.java:121)
        at org.itxtech.nemisys.network.SynapseInterface.processPackets(SynapseInterface.java:80)
        at org.itxtech.nemisys.network.SynapseInterface.process(SynapseInterface.java:101)
        at org.itxtech.nemisys.Server.tick(Server.java:381)
        at org.itxtech.nemisys.Server.tickProcessor(Server.java:353)
        at org.itxtech.nemisys.Server.start(Server.java:333)
        at org.itxtech.nemisys.Server.<init>(Server.java:173)
        at org.itxtech.nemisys.Nemisys.main(Nemisys.java:48)

19:06:43 [INFO] Client 127.0.0.1:7337 has disconnected due to Generic reason
```

**Comment by SleepSpace9** [comment]
I think you should wait for the SynapseAPI update in Genisys.

**Comment by NoHaxJustTryHqrd** [comment]
I get the exact same error

**Comment by boybook** [comment]
I think you should wait for the SynapseAPI update in Genisys or for Nukkit.

**Comment by NoHaxJustTryHqrd** [comment]
Ok!

**Comment by tarik02** [comment]
@boybook what update was? I can help to do it.

**Comment by alexbgameson** [comment]
I get that error aswell!

**Comment by DaMatrix** [comment]
The problem is that the networking protocol changed in the 0.16 update, and as Genisys 0.16 isn't production-ready yet, the version of synapse in there hasn't been updated.
