### ISSUE TITLE
Nemisys 0.16 Freezes

### ISSUE THREAD

**Issue by adamiss5138** [iTXTech/Nemisys#90]
0.15.x builds worked fine without any problem. For me all Nemisys 0.16 builds freeze after some time (10 - 30 mins)
No errors in log, but high CPU usage when it's frozen.

**Comment by DaMatrix** [comment]
that's been happening to me for some time too now, and is the reason i moved to genisys and then closed my server because it happened there too.

**Comment by XFuryMCPE** [comment]
Yeah. It just stops working and doesn't say any reason why. no one can join anymore

**Comment by XFuryMCPE** [comment]
I am thinking this could possibly be a problem caused when a 0.15.X player attempts to join the server.

**Comment by FilleDev** [comment]
I have the same issuse but mine takes like 24 hours. This issuse must be fixed!

**Comment by SupremeMortal** [comment]
No problems for me. I'm running ubuntu 16.04.

**Comment by jarne** [comment]
Me too. I'm guessing it's an issue with RackLib, because Nemisys is not completely frozen. You can't join and nothing happens when stopping the server, but console is still working.

**Comment by SleepSpace9** [comment]
Could this issue be solved by this commit: https://github.com/iTXTech/Nemisys/commit/98b486e3d638d66008f735f42a030f90155d39e1 ?

**Comment by boybook** [comment]
Yeah, I think you met the problem like me. This is because of 0.15.90.1 or 0.15.90.2. So I fixed by this commit: https://github.com/iTXTech/Nemisys/commit/98b486e3d638d66008f735f42a030f90155d39e1

**Comment by XFuryMCPE** [comment]
I'm using the newest version and this bug still occurs.

**Comment by xZeroMCPE** [comment]
Yeah, and the commit was added a few days..... My Nemisys was up-to-date. But same issue happens.

EDIT: Seems to be fixed, just had to do something

**Comment by jarne** [comment]
For me, 98b486e fixed all freezes, had no issues the last 24 hours.

**Comment by FilleDev** [comment]
Same @jjplaying

**Comment by adamiss5138** [comment]
After 20 hours uptime, latest Nemisys freezed with this error (I have no idea what does it mean :D)

`[WARNING] Network dropped connection on reset: no further information
java.net.SocketException: Network dropped connection on reset: no further information
    at sun.nio.ch.DatagramChannelImpl.receive0(Native Method)
    at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(Unknown Source)
    at sun.nio.ch.DatagramChannelImpl.receive(Unknown Source)
    at sun.nio.ch.DatagramChannelImpl.receive(Unknown Source)
    at io.netty.channel.socket.nio.NioDatagramChannel.doReadMessages(NioDatagramChannel.java:248)
    at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    at java.lang.Thread.run(Unknown Source)`
