### ISSUE TITLE
Nemisys timeouts

### ISSUE THREAD

**Issue by adamiss5138** [iTXTech/Nemisys#94]
I have the latest version of Nemisys. After a while (1 - 6 hours) timeouts with this error.

`[WARNING] Network dropped connection on reset: no further information
java.net.SocketException: Network dropped connection on reset: no further information
	at sun.nio.ch.DatagramChannelImpl.receive0(Native Method)
	at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.DatagramChannelImpl.receive(Unknown Source)
	at sun.nio.ch.DatagramChannelImpl.receive(Unknown Source)
	at io.netty.channel.socket.nio.NioDatagramChannel.doReadMessages(NioDatagramChannel.java:248)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)`

----------------------------
OS and versions
Genisys: #2205
Nemisys: latest 
PHP: 7.0.x
Server OS: WinServer 2012r2
Game version: 0.16.0.5
----------------------------

I have no idea what that error message means, but it annoys me.

**Comment by iPocket** [comment]
is your IP dynamic?

**Comment by adamiss5138** [comment]
Yes it is, but changes once a year
